### PR TITLE
Added HTML to standard and removed contact app

### PR DESCRIPTION
**Pull request by kzadrozny**
## Code
- removed `contact` app
- added `RawHTML` module to Standard Page template using the already existing `WebFeedBlock` streamfield.

## On Wagtail
- Kathy will unpublish current contact page and replace with a standard page with the CGIMail code
- Can see a working CGI form working on the test site, which is going to Kathy's email for testing purposes: https://bmrc-test.lib.uchicago.edu/contact

### CODE REVIEW

**Comment by kzadrozny** [comment]
@bbusenius Would love some input on how to make the CGI receipt load within the page itself rather than going to a new and unstyled page. If that is not possible, can we style the CGI mail page?

**Comment by kzadrozny** [comment]
@bbusenius This is the code I have within the HTML streamfield for the form to reload in-page. Right now it doesn't seem to even submit the form. You can view the admin for the form [on test](https://bmrc-test.lib.uchicago.edu/admin/pages/87/edit/):
```
<script>
  handleRedirect = (res) => {
    if (res.status === 200) {
      res.text().then((body) => {
        this.setState({
          submitted: true,
          response: body,
        });
      });
    } else {
      // TODO - Failure message
    }
  }

  handleSubmit = (e) => {
    e.preventDefault();
    const form = document.forms.cgimail;
    const data = new FormData(form);
    fetch('../cgi-bin/cgimail/cgimail', {
      method: 'POST',
      body: data,
    }).then(this.handleRedirect);
  }

  handleChange(e) {
    const { value } = e.target;
    this.setState({
      [e.target.name]: value,
    });
  }
</script>
```

**Comment by bbusenius** [comment]
One thing that jumps out to me is that nothing related to state is going to work. That's something you setup and work with in React. It won't exist in your JS. So, you will want to eliminate:

```
        this.setState({
          submitted: true,
          response: body,
        });
   ```
   in the handleRedirect function. I would replace it with a simple `console.log('Test')` for now, just to see if it works. Same for the `this.setState` in the handleChange function.

**Comment by bbusenius** [comment]
Also, `new FormData` won't work because that's a component we created in React. It won't exist in your JS.

**Comment by bbusenius** [comment]
This is a version stripped down a little more. It has a higher probability of success. I still don't think it will work but it will be closer:

```
<script>
  handleRedirect = (res) => {
    if (res.status === 200) {
      res.text().then((body) => {
        console.log('Test 1');
      });
    } else {
      // TODO - Failure message
    }
  }

  handleSubmit = (e) => {
    e.preventDefault();
    const form = document.forms.cgimail;
    const data = new FormData(form);
    fetch('../cgi-bin/cgimail/cgimail', {
      method: 'POST',
      body: data,
    }).then(this.handleRedirect);
  }

  handleChange(e) {
    const { value } = e.target;
    console.log(value);
  }
</script>
```

**Comment by bbusenius** [comment]
One thing you'll want to check is this. 

`const form = document.forms.cgimail;` is saying, "Get all forms in the document and used the one called 'cgimail'". So, you'll need to have a form with that name in the html. I'm not looking at the library website now but I think it just means the form has something like `name="cgimail"`. You'll want to confirm that. It could be an `id` too, I don't remember.

**Comment by kzadrozny** [comment]
@bbusenius This PR is ready for your review, with a working contact form on: https://bmrc-test.lib.uchicago.edu/contact
Opted to have script that simply loaded a success message for now. Will need to change this in a future code change so that it actually loads the receipt from CGIMail, which is critical in order to add required form fields.

**Comment by kzadrozny** [comment]
Code used, for future reference, if needed:
```
<script>
var successMessage = '<div class="notification form-success"><strong>Thank you for contacting BMRC.</strong><br/> We will reply to you shortly.</div>';

function handleRedirect (res) {
  if (res.status === 200) {
    res.text().then((body) => {
      document.getElementById("cgimail").innerHTML = successMessage;
      document.getElementById("submit-link").style.display = 'none';
    });
  }
}
function handleSubmit(e) {
  e.preventDefault();
  const form = document.forms.cgimail;
  const data = new FormData(form);
  fetch('../cgi-bin/cgimail/cgimail', {
    method: 'POST',
    body: data,
  }).then(handleRedirect);
}
function handleChange(e) {
  const { value } = e.target;
  console.log(value);
}
document.getElementById("submit-link").addEventListener("click", handleSubmit);
</script>
```

With HTML in the form:
`<form name="cgimail" onSubmit={handleSubmit}>` and `<button id="submit-link" class="button is-link">Submit</button>`

**Review by bbusenius — APPROVED** [review]
This looks good. The Javascript and post-submit styling you added to the contact form is a nice touch. It's a much better user experience.

**Pull request merged**
